l_english:
 anb_settings.1.t:0 "ƒ¡ ±¨®¢²¿ ¢:\n£settings_main_bg£"
 anb_settings.1.d:0 "§L                          ¡°¢®°ª «Ôº°º Ô®» — EU4 ¢ª¾ 1.36.1§!"
 anb_settings.1.a:0 "£settings_button_regions_menu£"
 anb_settings.1.b:0 "£settings_button_conquerors_menu£"
 anb_settings.1.bx:0 "£settings_button_conquerors_menu_g£"
 anb_settings.1.c:0 "£settings_button_achievements_off£"
 anb_settings.1.cx:0 "£settings_button_achievements_on£"
 anb_settings.1.s:0 "£settings_button_start_game£"
 anb_settings.1.empty:0 "£event_button_settings_empty£"

 anb_settings.2.t:0 "Ï®ª¬ª ©¢¢²®ª\n£settings_conqueror_bg£"
 anb_settings.2.d:0 ""
 anb_settings.2.a:0 "£settings_button_no_conqueror_g£"
 anb_settings.2.ax:0 "£settings_button_no_conqueror£"
 anb_settings.2.b:0 "£settings_button_conqueror_g£"
 anb_settings.2.bx:0 "£settings_button_conqueror£"
 anb_settings.2.c:0 "£settings_button_mythical_g£"
 anb_settings.2.cx:0 "£settings_button_mythical£"
 anb_settings.2.dd:0 "£settings_button_conqueror_variance_on£"
 anb_settings.2.ddx:0 "£settings_button_conqueror_variance_off£"
 anb_settings.2.x:0 "£settings_button_back_to_menu_2£"
 
 anb_settings.3.t:0 "£settings_regions_bg£\n    [Root.GetSettingsNorthAelantir]\n    [Root.GetSettingsCannor]\n    [Root.GetSettingsForbiddenPlains]\n    [Root.GetSettingsWestSerpentspine]\n    [Root.GetSettingsHaless]\n    [Root.GetSettingsDeepwoods]\n    [Root.GetSettingsBulwar]\n    [Root.GetSettingsEastSerpentspine]\n    [Root.GetSettingsRahen]\n    [Root.GetSettingsNorthSarhal]\n    [Root.GetSettingsInsyaa]\n    [Root.GetSettingsSouthAelantir]\n    [Root.GetSettingsSouthSarhal]"
 anb_settings.3.d:0 "\n\n\n\n[Root.GetSettingsAlertRed][Root.GetSettingsAlertOrange]"
 anb_settings.3.a:0 "£settings_button_north_aelantir££settings_alert_none£"
 anb_settings.3.ax:0 "£settings_button_north_aelantir_x£[Root.GetSettingsAlertNorthAelantir]"
 anb_settings.3.b:0 "£settings_button_south_aelantir££settings_alert_none£"
 anb_settings.3.bx:0 "£settings_button_south_aelantir_x£[Root.GetSettingsAlertSouthAelantir]"
 anb_settings.3.c:0 "£settings_button_cannor££settings_alert_none£"
 anb_settings.3.cx:0 "£settings_button_cannor_x£[Root.GetSettingsAlertCannor]"
 anb_settings.3.dd:0 "£settings_button_deepwoods££settings_alert_none£"
 anb_settings.3.ddx:0 "£settings_button_deepwoods_x£[Root.GetSettingsAlertDeepwoods]"
 anb_settings.3.e:0 "£settings_button_bulwar££settings_alert_none£"
 anb_settings.3.ex:0 "£settings_button_bulwar_x£[Root.GetSettingsAlertBulwar]"
 anb_settings.3.f:0 "£settings_button_north_sarhal££settings_alert_none£"
 anb_settings.3.fx:0 "£settings_button_north_sarhal_x£[Root.GetSettingsAlertNorthSarhal]"
 anb_settings.3.g:0 "£settings_button_south_sarhal££settings_alert_none£"
 anb_settings.3.gx:0 "£settings_button_south_sarhal_x£[Root.GetSettingsAlertSouthSarhal]"
 anb_settings.3.h:0 "£settings_button_west_serpentspine££settings_alert_none£"
 anb_settings.3.hx:0 "£settings_button_west_serpentspine_x£[Root.GetSettingsAlertWestSerpentspine]"
 anb_settings.3.i:0 "£settings_button_east_serpentspine££settings_alert_none£"
 anb_settings.3.ix:0 "£settings_button_east_serpentspine_x£[Root.GetSettingsAlertEastSerpentspine]"
 anb_settings.3.j:0 "£settings_button_forbidden_plains££settings_alert_none£"
 anb_settings.3.jx:0 "£settings_button_forbidden_plains_x£[Root.GetSettingsAlertForbiddenPlains]"
 anb_settings.3.k:0 "£settings_button_rahen££settings_alert_none£"
 anb_settings.3.kx:0 "£settings_button_rahen_x£[Root.GetSettingsAlertRahen]"
 anb_settings.3.l:0 "£settings_button_haless££settings_alert_none£"
 anb_settings.3.lx:0 "£settings_button_haless_x£[Root.GetSettingsAlertHaless]"
 anb_settings.3.m:0 "£settings_button_insyaa££settings_alert_none£"
 anb_settings.3.mx:0 "£settings_button_insyaa_x£[Root.GetSettingsAlertInsyaa]"
 anb_settings.3.x:0 "£settings_button_back_to_menu£"
 
 #custom loc
 settings_cannor_yes:0 "£settings_cannor£"
 settings_north_aelantir_yes:0 "£settings_north_aelantir£"
 settings_forbidden_plains_yes:0 "£settings_forbidden_plains£"
 settings_bulwar_yes:0 "£settings_bulwar£"
 settings_deepwoods_yes:0 "£settings_deepwoods£"
 settings_east_serpentspine_yes:0 "£settings_east_serpentspine£"
 settings_haless_yes:0 "£settings_haless£"
 settings_north_sarhal_yes:0 "£settings_north_sarhal£"
 settings_rahen_yes:0 "£settings_rahen£"
 settings_west_serpentspine_yes:0 "£settings_west_serpentspine£"
 settings_insyaa_yes:0 "£settings_insyaa£"
 settings_south_aelantir_yes:0 "£settings_south_aelantir£"
 settings_south_sarhal_yes:0 "£settings_south_sarhal£"
 settings_no:0 ""
 
 settings_alert_orange:0 "£settings_alert_orange£"
 settings_alert_red:0 "£settings_alert_red£"
 settings_alert_red_orange:0 "£settings_alert_red_orange£"
 settings_alert_none:0 "£settings_alert_none£"
 
 settings_alert_orange_main:0 "£settings_alert_orange_main£"
 settings_alert_red_main:0 "£settings_alert_red_main£\n"
 settings_alert_none_main:0 ""
 
 #tooltip
 settings_achievement_tt:0 "²¬®½¶°ª ¦²ª¨°ªþ ¯¨² ±ª¢²ª ¬ (¶°¿) °©°¶ª²®¿°¯³ ³¢®ª¶°ª½ ±ª©¢¦ª²®¿°²ª ª¥º"
 settings_achievement_disabled_tt:0 "§Rƒ²ª¨°ª¾ ° ¯¥³² ¡º²¿ ¢¬®½¶°º ¢ ¯°¥±®¿©¢²®¿¬þ ª¥§!"
 
 great_conqueror_tooltip:0 "™² ±µª¾ ¬²ª¢ª³² §YÏ®ª¬ª ©¢¢²®þ§!, ¶²¡º ¦®²¿ ª¥³ ¡® ®¨°þ."
 mythical_conqueror_tooltip:0 "«Ù³º ª©¡¥½² ¢º©¢¢, ®¡¬ª ³¦ª½² ² °ª,  ¢ª°º ±¦¯ª¥ª¢½² ª¯.»\n\n™² ±µª¾ ±©¢®ª² ¢¬®½¶ª²¿ §Yª´ª¶¬ª ©¢¢²®þ§!, ¡® ¼¬²¯®¿°³½ ¢ª½ §YÏ®ª¬ª ©¢¢²®þ§!."
 random_conqueror_targets_tooltip:0 "§RWIP, ±¬ °ª¶¥ ° ¦®²§!"
 
 settings_conquerors_tt:0 "§YÏ®ª¬ª ©¢¢²®ª§!\nƒª°¯ª¶¬ª ¢º¡ª¯º ²°º †† ±®³¶² ¡°³º, ¬²º ±¯¥³² ª¯ ¬°®ª¦ª¢²¿ ¢ž ¬³¨°ª, ª ²°³² ¡® ®¨°º¯ª ±²ª¢°ª¬¯ª ¢ ¦°þ ª ±©¦°þ ª¥."
 settings_regions_tt:0 "§Y²¬®½¶°ª ¥ª°¢§!\n²¬®½¶°ª °¬²º ¶²þ ¯ª ±©¢®ª² ¢¯ ³®³¶Œª²¿ ±ª©¢¦ª²®¿°²¿ ª¥º."
 settings_needs_rom_dlc_tt:0 "§Rƒ®¾ ¼²þ ´³°¬µªª ²¡³²¾ DLC Rights of Man.§!"
 institutions_warning_tt:0 "£icon_settings_alert_red£ §R²¬®½¶°ª °° ° ±©¢®ª² °¬²º¯ ª°²ª²³²¯ ¢©°ª¬²¿ ¬¬²°§!\n"
 tag_need_this_region_tt:0 "£icon_settings_alert_orange£ §y[Root.GetName] ¯¨² ª¯²¿ ¬°²°², ¢¾©°°ºþ  ¼²ª¯ ¥ª°¯§!"
 tag_in_this_region_tt:0 "£icon_settings_alert_red£ §RÔ²®ªµ [Root.GetName] °¦ª²¾ ¢ ¼²¯ ¥ª°§!\n"
 disable_region_tt:0 "²¬®½¶°ª ¼²þ ¡®²ª ±©¢®¾² ±¢ºª²¿ ±ª©¢¦ª²®¿°²¿ ª¥º.\n---------------------------\n"
 settings_wont_be_available_tt:0 "§R²þ¬ª ¦²³±°º ²®¿¬ ¢ °¶® ª¥º, ±©¨ ¢º ° ¯¨² ±®³¶ª²¿ ¬ °ª¯ ¦²³±.§!"
 settings_regions_are_gonna_get_removed_tt:0 "£icon_settings_alert_red£ §R²¬®½¶°°º ¥ª°º ¡³¦³² ³¦®°º ª© ª¥º, ª ¢º ° ¯¨² ¦¡¢ª²¿ ª ¡²°. ™² ¦þ²¢ª ¯¨² ±ª¢²ª ¬ ©¦¨¬ ª¥º ° ±³ ¬³°¦.§!"
